#include <Arduino.h>
#include "arm_defines.h"
unsigned long pinStart(){
  pinMode(ENABLE_A_A,OUTPUT);
  pinMode(ENABLE_A_B,OUTPUT);
  pinMode(ENABLE_B_A,OUTPUT);
  pinMode(ENABLE_B_B,OUTPUT);
  pinMode(ENABLE_C_A,OUTPUT);
  pinMode(ENABLE_C_B,OUTPUT);
  pinMode(SERVO_1,OUTPUT);
  pinMode(SERVO_2,OUTPUT);
  pinMode(SERVO_3,OUTPUT);
  pinMode(SERVO_4,OUTPUT);
  pinMode(CS_0,OUTPUT);
  pinMode(CS_1,OUTPUT);
  pinMode(IN_A_A_1,OUTPUT);
  pinMode(IN_A_A_2,OUTPUT);
  pinMode(IN_A_B_1,OUTPUT);
  pinMode(IN_A_B_2,OUTPUT);
  pinMode(IN_B_A_1,OUTPUT);
  pinMode(IN_B_A_2,OUTPUT);
  pinMode(IN_B_B_1,OUTPUT);
  pinMode(IN_B_B_2,OUTPUT);
  pinMode(IN_C_A_1,OUTPUT);
  pinMode(IN_C_A_2,OUTPUT);
  pinMode(IN_C_B_1,OUTPUT);
  pinMode(IN_C_B_2,OUTPUT);
  pinMode(WIZNET_CS,OUTPUT);
  pinMode(WIZNET_INT,OUTPUT);
  pinMode(WIZNET_RS,OUTPUT);
  pinMode(SERVO_ENABLE_1,OUTPUT);
  pinMode(SERVO_ENABLE_2,OUTPUT);
  pinMode(SERVO_ENABLE_3,OUTPUT);
  pinMode(SERVO_ENABLE_4,OUTPUT);
  pinMode(ALERT,OUTPUT);
  pinMode(BOURNS_DATA,OUTPUT);
  pinMode(BOURNS_CLOCK,OUTPUT);
  pinMode(BOURNS_CS,OUTPUT);
  pinMode(NEOPIXEL,OUTPUT);

  pinMode(SENS_A_A,INPUT);
  pinMode(SENS_A_B,INPUT);
  pinMode(SENS_B_A,INPUT);
  pinMode(SENS_B_B,INPUT);
  pinMode(SENS_C_A,INPUT);
  pinMode(SENS_C_B,INPUT);
  pinMode(SENS_SERVO_1,INPUT);
  pinMode(SENS_SERVO_2,INPUT);
  pinMode(SENS_SERVO_3,INPUT);
  pinMode(SENS_SERVO_4,INPUT);
  pinMode(PH,INPUT);
  pinMode(FINGER_ENCODER,INPUT);
}