spring:
    application:
        name: rover-controller-service

logging:
  level:
    root: INFO
    '[pl.orion]': DEBUG

server:
    port: 8880
    shutdown: graceful

mqtt:
    clientId: rover-controller-service
    broker:
        url: ${MQTT_BROKER_URL}
        port: 1883
        username: ${MQTT_USERNAME}
        password: ${MQTT_PASSWORD}
    connection:
        timeout.ms: 5000
        keepalive.ms: 60000
        reconnect.delay.ms: 5000

chassis:
    eventType: chassis
    downstream:
        inbound: orion/topic/chassis/inbound
        outbound: orion/topic/chassis/outbound
    upstream:
        inbound: orion/topic/chassis/controller/inbound
