spring:
  main:
    banner-mode: off
  application:
    name: uart-mqtt-gateway
  config:
    import:
    - classpath:uart-mqtt-gateway.yml

logging:
  level:
    root: INFO
    '[pl.orion]': DEBUG

server:
  port: 8088