spring:
  main:
    banner-mode: off
  application:
    name: uart-mqtt-gateway
  config:
    import:
    - classpath:uart-mqtt-gateway.yml

logging:
  level:
    root: INFO
    '[pl.orion]': DEBUG

server:
  port: 8088

management:
  endpoint:
    shutdown:
      access: unrestricted
  endpoints:
    web:
      exposure:
        include: health, shutdown